import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { EdgeDBProvider } from "@/app/EdgeDBProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-background font-sans `}>
        <EdgeDBProvider>{children}</EdgeDBProvider>
      </body>
    </html>
  );
}

export const preferredRegion = ["cle1"];
